jest.mock('../entities/observation.entity', () => ({
    ObservationEntity: class ObservationEntity { },
}));

import { ObservationsService } from './observations.service';

describe('ObservationsService.findFormData station-ID TRIM matching', () => {
    let mockFindBy: jest.Mock;

    function createService() {
        mockFindBy = jest.fn().mockResolvedValue([]);

        const service = new ObservationsService(
            { findBy: mockFindBy } as any,
            {} as any,
            {} as any,
            {} as any,
            { emit: jest.fn() } as any,
            {} as any,
            {} as any,
            { findSourcesByIds: () => [] } as any,
            {} as any,
        );

        return service;
    }

    function getStationIdArg(): unknown {
        return mockFindBy.mock.calls[0][0].stationId;
    }

    it('uses a Raw SQL expression (not a plain string) so TRIM is applied on the DB column', async () => {
        const service = createService();

        await service.findFormData({
            stationId: 'LESLER01',
            elementIds: [2],
            interval: 1440,
            sourceId: 4,
            level: 0,
            fromDate: '2026-04-01T00:00:00.000Z',
            toDate: '2026-04-29T23:00:00.000Z',
        });

        expect(mockFindBy).toHaveBeenCalledTimes(1);
        const stationIdArg = getStationIdArg();

        // Must not be a plain string – it must be a FindOperator wrapping a Raw expression
        expect(typeof stationIdArg).not.toBe('string');
        expect(stationIdArg).not.toBeNull();

        // The SQL generated by the Raw expression must contain TRIM
        const generated: string = (stationIdArg as any)._getSql('station_id');
        expect(generated).toContain('TRIM(station_id)');

        // The bound parameter must be the trimmed station ID
        const params = (stationIdArg as any)._objectLiteralParameters;
        expect(params.stationId).toBe('LESLER01');
    });

    it('trims leading/trailing whitespace from stationId before passing to the query', async () => {
        const service = createService();

        await service.findFormData({
            stationId: '  LESLER01  ',
            elementIds: [2],
            interval: 1440,
            sourceId: 4,
            level: 0,
            fromDate: '2026-04-01T00:00:00.000Z',
            toDate: '2026-04-29T23:00:00.000Z',
        });

        const stationIdArg = getStationIdArg();
        const params = (stationIdArg as any)._objectLiteralParameters;
        expect(params.stationId).toBe('LESLER01');
    });
});
