apiVersion: v1
kind: Namespace
metadata:
  name: climate-ai
  labels:
    app.kubernetes.io/name: climate-ai
    app.kubernetes.io/part-of: climsoft-web
    project: ai-enhanced-cdms
    country: lesotho
